title: CSEHY Benefit Concert
description: Benefit concert to raise funds for four young musicians to attend summer music camp.
baseurl: "" # set to "" for user/organization pages; set to "/repo-name" if using project page
url: "https://KurtKroeker.github.io/csehy-fundraising" # replace with final site URL or custom domain
markdown: kramdown
collections:
  performers:
    output: true
    permalink: /performers/:name/